### ISSUE TITLE
instances.setIssuer always throws

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-vc-issuer#24]
First these asserts are written incorrectly:

```
const assert = require('assert-plus');
assert.object('foo', {});
Thrown:
{ AssertionError [ERR_ASSERTION]: [object Object] (object) is required
    at new AssertionError (internal/assert/assertion_error.js:401:11)
    at _toss (/work/ajones/digital_bazaar/bedrock-edv-storage/node_modules/assert-plus/assert.js:22:11)
    at Function.out.(anonymous function) [as object] (/work/ajones/digital_bazaar/bedrock-edv-storage/node_modules/assert-plus/assert.js:122:17)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: 'string',
  expected: 'object',
  operator: '===' }
```

the first argument to assert should be the object itself the second is the label
additionally these asserts are written incorrectly:

```
const assert = require('assert-plus');
assert.object('foo', {});
Thrown:
{ AssertionError [ERR_ASSERTION]: [object Object] (object) is required
    at new AssertionError (internal/assert/assertion_error.js:401:11)
    at _toss (/work/ajones/digital_bazaar/bedrock-edv-storage/node_modules/assert-plus/assert.js:22:11)
    at Function.out.(anonymous function) [as object] (/work/ajones/digital_bazaar/bedrock-edv-storage/node_modules/assert-plus/assert.js:122:17)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: 'string',
  expected: 'object',
  operator: '===' }
```

the first argument to assert should be the object itself the second is the label

```
assert.object({}, 'foo');

// this throws with a label for the object
Thrown:
{ AssertionError [ERR_ASSERTION]: foo (object) is required
    at new AssertionError (internal/assert/assertion_error.js:401:11)
    at _toss (/work/ajones/digital_bazaar/bedrock-edv-storage/node_modules/assert-plus/assert.js:22:11)
    at Function.out.(anonymous function) [as object] (/work/ajones/digital_bazaar/bedrock-edv-storage/node_modules/assert-plus/assert.js:122:17)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: 'boolean',
  expected: 'object',
  operator: '===' }
```

This might be due to a misunderstanding, but

https://github.com/digitalbazaar/bedrock-mongodb/blob/1763e945eabe88e3e34acf71dc287646c5e7314b/lib/index.js#L258-L267
```js
api.hash = key => {
  if(typeof key !== 'string') {
    throw new BedrockError(
      'Invalid key given to database hash method.',
      'InvalidKey', {key});
  }
  const md = crypto.createHash('sha256');
  md.update(key, 'utf8');
  return md.digest('base64');
};
```

`database.hash` expects a string and throws if the key is not a string.

https://github.com/digitalbazaar/bedrock-vc-issuer/blob/18a5f68047b56796c0f749b871dcd2cedfc46d61/lib/instances.js#L178-L182

setIssuer expects `issuer` to be an object

it then calls on `database.hash(issuer)` which has to be an object.

**Comment by dlongley** [comment]
Set issuer doesn't exist any more, closing.
